### ISSUE TITLE
Bounty Source?

### ISSUE THREAD

**Issue by jlgore** [tuudik/osticket-rocketchat#2]
I think this is a very useful plugin. I'd love to contribute something back, but I'm not a coder. Would you be into working with Bounty Source or a direct donation?

**Comment by tuudik** [comment]
What kind of feature would you like it to have?

Just in case, i'm not a daily programmer too, but perhaps I can manage to figure it out :)

**Comment by jlgore** [comment]
I don't necessarily need any extra features at the moment (just got it working recently). Just wanted to support you for doing awesome work.

**Comment by tuudik** [comment]
My PayPal is marko@radr.eu

PS! I had to think about it 10 times, before I decided to share my PayPal, because I don't feel worthy for any direct donations :) But, I will assure you that I will forward the donation for some other open-source project whom I appreaciate for doing awesome stuff :)

**Comment by jlgore** [comment]
Sent you a little love. Thanks for such an awesome project!

**Comment by tuudik** [comment]
Thanks man! :smile:
